<?php
include "header.php";
?>

<section class="banner-area organic-breadcrumb" style="">
	<div class="container">
		<div class="breadcrumb-banner d-flex flex-wrap align-items-center">
			<div class="col-first">
				<h2 class="">Disclaimer</h2>
                 <!-- <nav class="d-flex align-items-center justify-content-start">
                    <a href="#">About Us<i class="fa fa-caret-right" aria-hidden="true"></i></a>
                    <a href="#">About Us</a>
                </nav> -->
            </div>
        </div>
    </div>
</section>
<!-- Start My Account -->
<div class="container">
	<div class="row">
		<div class="col-xl-12 col-lg-12 col-md-12">
			<section class="category-area section-gap" id="about-us">
				<div class="container">
					<div class="row d-flex justify-content-center">
						<div class="menu-content">
							<p align="justify">1.
								THE WEBSITE, SERVICES AND OTHER MATERIALS ARE PROVIDED BY KAINKARYA CHARITABLE TRUST ON AN
								"AS IS" BASIS WITHOUT WARRANTY OF ANY KIND, EXPRESS, IMPLIED, STATUTORY OR OTHERWISE, INCLUDING
								THE IMPLIED WARRANTIES OF TITLE, NON-INFRINGEMENT, MERCHANTABILITY OR FITNESS FOR A PARTICULAR
								PURPOSE. WITHOUT LIMITING THE FOREGOING, KAINKARYA CHARITABLE TRUST MAKES NO WARRANTY THAT
							</p><br>
							<p align="justify">(I) THE WEBSITE OR THE SERVICES WILL MEET YOUR REQUIREMENTS OR YOUR USE OF THE WEBSITE OR THE
								SERVICES WILL BE UNINTERRUPTED, TIMELY, SECURE OR ERROR-FREE;						
							</p>
							<p align="justify">(II) THE RESULTS THAT MAY BE OBTAINED FROM THE USE OF THE WEBSITE, SERVICES OR MATERIALS WILL BE
								EFFECTIVE, ACCURATE OR RELIABLE;						
							</p>
							<p align="justify">
								(III) THE QUALITY OF THE WEBSITE, SERVICES OR OTHER MATERIALS WILL MEET YOUR EXPECTATIONS; OR THAT					
							</p>
							<p align="justify">
								(IV) ANY ERRORS OR DEFECTS IN THE WEBSITE, SERVICES OR OTHER MATERIALS WILL BE CORRECTED. NO
								ADVICE OR INFORMATION, WHETHER ORAL OR WRITTEN, OBTAINED BY YOU FROM KAINKARYA CHARITABLE
								TRUST OR THROUGH OR FROM USE OF THE SERVICES SHALL CREATE ANY WARRANTY NOT EXPRESSLY STATED IN
								THE TERMS OF USE.				
							</p><br>
							<p align="justify">
								2. TO THE MAXIMUM EXTENT PERMITTED BY APPLICABLE LAW, KAINKARYA CHARITABLE TRUST WILL HAVE NO
								LIABILITY RELATED TO USER CONTENT ARISING UNDER INTELLECTUAL PROPERTY RIGHTS, LIBEL, PRIVACY,
								PUBLICITY, OBSCENITY OR OTHER LAWS. KAINKARYA CHARITABLE TRUST ALSO DISCLAIMS ALL LIABILITY WITH
								RESPECT TO THE MISUSE, LOSS, MODIFICATION OR UNAVAILABILITY OF ANY USER CONTENT.						
							</p><br>
							<p align="justify">3. KAINKARYA CHARITABLE TRUST WILL NOT BE LIABLE FOR ANY LOSS THAT YOU MAY INCUR AS A
								CONSEQUENCE OF UNAUTHORIZED USE OF YOUR ACCOUNT OR ACCOUNT INFORMATION IN CONNECTION WITH
								THE WEBSITE OR ANY SERVICES OR MATERIALS, EITHER WITH OR WITHOUT YOUR KNOWLEDGE. KAINKARYA
								CHARITABLE TRUST HAS ENDEAVORED TO ENSURE THAT ALL THE INFORMATION ON THE WEBSITE IS CORRECT,
								BUT KAINKARYA CHARITABLE TRUST NEITHER WARRANTS NOR MAKES ANY REPRESENTATIONS REGARDING THE
								QUALITY, ACCURACY OR COMPLETENESS OF ANY DATA, INFORMATION, PRODUCT OR SERVICE. KAINKARYA
								CHARITABLE TRUST SHALL NOT BE RESPONSIBLE FOR THE DELAY OR INABILITY TO USE THE WEBSITE OR
								RELATED FUNCTIONALITIES, THE PROVISION OF OR FAILURE TO PROVIDE FUNCTIONALITIES, OR FOR ANY
								INFORMATION, SOFTWARE, PRODUCTS, FUNCTIONALITIES AND RELATED GRAPHICS OBTAINED THROUGH THE
								WEBSITE, OR OTHERWISE ARISING OUT OF THE USE OF THE WEBSITE, WHETHER BASED ON CONTRACT, TORT,
								NEGLIGENCE, STRICT LIABILITY OR OTHERWISE. FURTHER, KAINKARYA CHARITABLE TRUST SHALL NOT BE HELD
								RESPONSIBLE FOR NON-AVAILABILITY OF THE WEBSITE DURING PERIODIC MAINTENANCE OPERATIONS OR ANY
								UNPLANNED SUSPENSION OF ACCESS TO THE WEBSITE THAT MAY OCCUR DUE TO TECHNICAL REASONS OR FOR
								ANY REASON BEYOND KAINKARYA CHARITABLE TRUST'S CONTROL. THE USER UNDERSTANDS AND AGREES THAT
								ANY MATERIAL OR DATA DOWNLOADED OR OTHERWISE OBTAINED THROUGH THE WEBSITE IS DONE ENTIRELY AT
								THEIR OWN DISCRETION AND RISK AND THEY WILL BE SOLELY RESPONSIBLE FOR ANY DAMAGE TO THEIR
								COMPUTER SYSTEMS OR LOSS OF DATA THAT RESULTS FROM THE DOWNLOAD OF SUCH MATERIAL OR DATA.
								KAINKARYA CHARITABLE TRUST IS NOT RESPONSIBLE FOR ANY TYPOGRAPHICAL ERROR LEADING TO AN INVALID
								COUPON. KAINKARYA CHARITABLE TRUST ACCEPTS NO LIABILITY FOR ANY ERRORS OR OMISSIONS, WITH
								RESPECT TO ANY INFORMATION PROVIDED TO YOU WHETHER ON BEHALF OF ITSELF OR THIRD PARTIES.						
							</p><br>
							<p align="justify">
								4. KAINKARYA CHARITABLE TRUST SHALL NOT BE LIABLE FOR ANY THIRD PARTY PRODUCT OR SERVICES. THE
								ADVERTISEMENT AVAILABLE ON E-MAIL OR WEBSITE WITH RESPECT TO THE THIRD PARTY WEBSITE OR THE
								PRODUCTS AND SERVICES ARE FOR INFORMATION PURPOSE ONLY				
							</p><br>
							<p align="justify">5. KAINKARYA CHARITABLE TRUST DOES NOT CONTROL, ENDORSE OR ACCEPT RESPONSIBILITY FOR ANY
								PRODUCT (INCLUDING BUT NOT LIMITED TO PRODUCT CATALOGUES) OR SERVICES OFFERED BY THIRD PARTIES
								ACCESSIBLE THROUGH THE WEBSITE OR ANY LINKED SITES. KAINKARYA CHARITABLE TRUST MAKES NO
								REPRESENTATIONS OR WARRANTIES WHATSOEVER ABOUT, AND SHALL NOT BE LIABLE FOR, THE VENDOR OR ANY
								SUCH THIRD PARTIES, THEIR PRODUCTS OR SERVICES, INCLUDING REPRESENTATIONS RELATING TO NON-
								INFRINGEMENT OF THIRD PARTY INTELLECTUAL PROPERTY RIGHTS. ANY TRANSACTIONS THAT YOU MAY HAVE
								WITH SUCH THIRD PARTIES ARE AT YOUR OWN RISK. THE PRODUCTS SHALL BE SUBJECT TO VENDOR'S TERMS
								AND CONDITIONS AND KAINKARYA CHARITABLE TRUST DOES NOT ACCEPT ANY RESPONSIBILITY FOR THE SAME.
								KAINKARYA CHARITABLE TRUST ALSO DOES NOT ACCEPT ANY RESPONSIBILITY FOR THE USAGE OF THE
								PRODUCTS BY YOU.				
							</p>
							
							
						</div>
					</div>					
				</div>	
			</section>			
		</div>
	</div>
</div>
<!-- End My Account -->

<?php
include "footer.php";
?>